# use v3.8 docker compose
version: "3.8"
# services definitions
services:  
# item-app service
  item-app:
# pull image from github packages / username / packages / version
    image: ghcr.io/mishbahulm/item-app:v1
# ports expost list
    ports:
# port expost from 8080 (container) to 80 (host)
      - 80:8080
# item-app service are depends on service(s) create first from this list
    depends_on:
# item-app service is depends on item-db service
      - item-db
# always restart the container if it stops
    restart: always
# item-db service
  item-db:
# pull image from docker hub
    image: mongo:3
# persistence storage volume type
    volumes:
# app-db host directory from /data/db in container
      - app-db:/data/db 
# always restart the container if it stops
    restart: always
# create docker volumes
volumes:
# volume name app-db
  app-db: