version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable
  go:
    docker:
      - image: cimg/go:1.21.3

jobs:
  lint-dockerfile:
    executor: go
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    executor: go
    steps:
      - checkout
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push          
          # command: |
          #   docker build -t munirm3/karsajobs:latest .            
          #   echo $PASSWORD_DOCKER_HUB | docker login ghcr.io -u mishbahulm --password-stdin
          #   docker push munirm3/karsajobs:latest
          command: |
            build -t ghcr.io/mishbahulm/karsajobs:latest 
            echo $PASSWORD_DOCKER_HUB | docker login ghcr.io -u mishbahulm --password-stdin
            docker push ghcr.io/mishbahulm/karsajobs:latest

workflows:
  version: 2
  backend-deploy:
    jobs:
      # - lint-dockerfile
      # - test-app
      - build-app-karsajobs
