version: 2.1

workflows:
  test-deploy:
    jobs:
      - test1

jobs:
  test1:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run:
          name: Run test
          command: go test -v -short --count=1 $(go list ./...)