version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable
  go:
    docker:
      - image: cimg/go:1.21.3

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    executor: go
    steps:
      - checkout
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image App
          command: docker build -t ghcr.io/mishbahulm/karsajobs:latest .
      - run:
          name: Login to github
          # command: echo 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 | docker login ghcr.io -u mishbahulm --password-stdin
          command: docker login ghcr.io -u mishbahulm --password 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
      - run:
          name: Push the image
          command: docker push ghcr.io/mishbahulm/karsajobs:latest

workflows:
  version: 2
  backend-deploy:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
