# version: 2.1

# workflows:
#   backend-deploy:
#     jobs:
#       - backend

# jobs:
#   backend:
#     docker:
#       - image: cimg/go:1.21.3
#     steps:
#       - checkout
#       - run:
#           name: lint-dockerfile
#       - run:
#           name: test-app
#           command: go test -v -short --count=1 $(go list ./...)

version: '2.1'
orbs:
  docker: circleci/go@1.9.0
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io,my-company.com:5000
